
# This function 1) imports run information from the BoL analyst and
# 2) marks the incoming raw data with this information

# This outputs a dataframe ready for the processing scripts derived from the Excel sheets that
# Wiley Evans developed for Tribally-run BoLs.

# This function assumes the analyst has done the following things to the raw DscSmpl file generated by the BoL before starting:
# 1) only the gas and liquid standard runs that will be used for sample correction are included 
  # This specifically expects one set of each before the samples, within the samples, and after the samples.
# 2) The sample names exactly match what is recorded in any local inventory (whatever will tie them to in-situ temperatures)
# 3) The salinity for each sample is correct and reflects the lab-measured value.
# 4) Any CRMs in the run that are NOT being used for correction (e.g., are being used as samples) do not have "CRM" in the
  # sample name. If they are the same batch as the corrective CRMs, they may have "crm" in the sample name. 


library("tidyverse")
library("data.table")


f1 <- function(run_number = 1, run_date = "YYYY-MM-DD", analyst = "NAME", lab_temp = 18, roomair_co2 = 420,
               bol_data = "cleaned_DscSmpl", data_filepath = "path_to_raw_bol_data_files", crm_batch = 210,
               crm_batch_info = "path_to_crm_batch_info", sample_inventory = "path_to_inventory"){
  
  # Get the discrete data (this is what used to be copied and pasted into Wiley's google sheets)
  df <- read_csv(bol_data)
  
  year <- year(ymd(run_date))
  
  # Append the run number, the analysis date (in GMT), and the analyst to the data
  df <- df |> 
    mutate(analysis_date_AK = ymd(run_date)) |> 
    mutate(dttm_pco2 = as.POSIXct(DOY_pCO2, origin = ymd(paste0(year, "-01-01")))) |> 
    mutate(dttm_tco2 = as.POSIXct(DOY_TCO2, origin = ymd(paste0(year, "-01-01")))) |> 
    mutate(datetime = as.POSIXct(ifelse(is.na(dttm_tco2), dttm_pco2, dttm_tco2))) |> 
    mutate(julian_dt = ifelse(is.na(DOY_TCO2), DOY_pCO2, DOY_TCO2)) |> 
    mutate(analyst = analyst) |> 
    mutate(run_number = run_number) |> 
    mutate(lab_temp = lab_temp) |> 
    mutate(roomair_co2 = roomair_co2) |> 
    select(run_number, analysis_date_AK, analyst, datetime, julian_dt, Sample_ID, DOY_TCO2, TCO2_xCO2, DOY_pCO2, pCO2_xCO2, pCO2_Hdspc_P, pCO2_analysis_T, Smpl_S,
           dttm_pco2, dttm_tco2, lab_temp, roomair_co2) |> 
    arrange(julian_dt) |> 
    filter(!is.na(julian_dt))
  
  
  ## Label gas standards, liquid standards, and crms
  # Need to be flexible enough to group things in sets regardless of how many things are in that set. 
  # For gas and liquid standards, can use replicates of sample names.
  setDT(df)
  
  df <- df |> 
    mutate(type = case_when(str_detect(Sample_ID, "gstd") == TRUE | str_detect(Sample_ID, "Atm") == TRUE ~ "gas standard",
                            str_detect(Sample_ID, "lstd") == TRUE ~ "liquid standard",
                            str_detect(Sample_ID, "CRM") == TRUE | str_detect(Sample_ID, "crm") == TRUE ~ "CRM",
                            str_detect(Sample_ID, "IRM") == TRUE ~ "IRM",
                            TRUE ~ "sample")) |> 
    group_by(Sample_ID) |> 
    mutate(name_rep = row_number()) |> 
    ungroup() |> 
    mutate(set = case_when(type == "sample" ~ NA_character_,
                           type == "CRM" ~ paste0("crm", rleid(type)),
                           type == "gas standard" ~ paste0("gstd", name_rep),
                           type == "liquid standard" ~ paste0("lstd", name_rep))) |> 
    select(-c(name_rep)) |> 
    arrange(julian_dt)
  
  # Get indicies of the relevant sets and average times
  gstd_sets <- df |> filter(type == "gas standard") |> 
    group_by(set) |> 
    summarize(average_dt = mean(julian_dt)) |> 
    arrange(average_dt)
  lstd_sets <- df |> filter(type == "liquid standard") |> 
    group_by(set) |> 
    summarize(average_dt = mean(julian_dt)) |> 
    arrange(average_dt)
  crm_sets <- df |> filter(type == "CRM") |> 
    group_by(set) |> 
    summarize(average_dt = mean(julian_dt)) |> 
    arrange(average_dt)
  
  # Get name index for the gas and liquid standards
  gstd_names <- df |> filter(set == gstd_sets$set[1]) |> 
    filter(str_detect(Sample_ID, "Atm") == FALSE) |> 
    select(Sample_ID) |> unlist()
  
  lstd_names <- df |> filter(set == lstd_sets$set[1]) |> 
    select(Sample_ID) |> unlist()
  
  # Get timestamps for the first sample
  first_sample <- min(df$julian_dt[which(df$type == "sample")])
  
  
  # Finally, need to get the atmospheric pressure from the Gstd fit file(s). Might as well pull the standard values from here too
  # Same deal with the liquid standards. Eliminates need for analyst to input the standard values.
  
  # Identify the std fit files closest to the run.
  bol_file_list <- data.frame(files = list.files(data_filepath))
  bol_file_list <- bol_file_list |> 
    mutate(filestart = str_sub(files, -12)) |> 
    mutate(type = case_when(str_detect(files, "Gstd") == TRUE ~ "gstd fit",
                            str_detect(files, "Lstd") == TRUE ~ "lstd fit",
                            TRUE ~ "other")) |> 
    filter(type != "other") |> 
    mutate(filestart = parse_number(filestart)) |> 
    mutate(datetime = ymd_hm(filestart)) |> 
    mutate(doy = yday(datetime) + (hour(datetime) * 3600 + minute(datetime) * 60 + second(datetime)) / 86400) |> 
    filter(!is.na(datetime)) |> 
    mutate(time_to_samples = first_sample - doy) |> 
    filter(time_to_samples > 0) |>
    group_by(type) |> 
    mutate(min_difference = min(time_to_samples)) |> 
    ungroup() |> 
    filter(time_to_samples == min_difference)
  
  gstarget <- read_table(file = paste0(data_filepath, bol_file_list$files[which(bol_file_list$type == "gstd fit")]), skip = 3)
  if(ncol(gstarget) == 10){
    names(gstarget) <- c("DOY_UTC", "m_std", "b_std", "Rsq_std", "atm_ppm", "atm_P", "gs1", "gs2", "gs3", "gs4")
  } else if (ncol(gstarget) == 9){
    names(gstarget) <- c("DOY_UTC", "m_std", "b_std", "Rsq_std", "atm_ppm", "atm_P", "gs1", "gs2", "gs3")
  } else {
    names(gstarget) <- c("DOY_UTC", "m_std", "b_std", "Rsq_std", "atm_ppm", "atm_P", "gs1", "gs2")
  }
  
  lstarget <- read_table(file = paste0(data_filepath, bol_file_list$files[which(bol_file_list$type == "lstd fit")]), skip = 3)
  if(ncol(lstarget) == 9){
    names(lstarget) <- c("DOY_UTC", "m_std", "b_std", "Rsq_std", "atm_ppm", "atm_P", "ls1", "ls2", "ls3")
  } else {
    names(lstarget) <- c("DOY_UTC", "m_std", "b_std", "Rsq_std", "atm_ppm", "atm_P", "ls1", "ls2")
  } 
  
  # Extract the atmospheric pressure reading from the gstd fit closest to the first sample
  atm_P <- gstarget$atm_P[which(gstarget$DOY_UTC-first_sample == min(gstarget$DOY_UTC-first_sample))]
  
  
  # Make standard dataframes that have the standard values and the official names. I can then use these for the fits
  # later.
  rel_gs <- gstarget |> 
    select(cols = contains("gs")) |> 
    pivot_longer(cols = everything(), names_to = "std_order", values_to = "std_value") |> 
    distinct() |> 
    mutate(std_order = parse_number(std_order)) |> 
    mutate(std_names = gstd_names)
  
  rel_ls <- lstarget |> 
    select(cols = contains("ls")) |> 
    pivot_longer(cols = everything(), names_to = "std_order", values_to = "std_value") |> 
    distinct() |> 
    mutate(std_order = parse_number(std_order)) |> 
    mutate(std_names = lstd_names)
  
  
  ## Export the standard information (rel_gs, rel_ls), atm_P, and sample df
  list(gs_ref = rel_gs, ls_ref = rel_ls, atm_P = atm_P, fullrun = df, crm_batch = crm_batch,
       crm_batch_info_path = crm_batch_info, sample_inventory_path = sample_inventory)
  
  
}


